version: "3.8"

services:
  db:
    image: postgres:13.3
    restart: always
    healthcheck:
      test: ["CMD", "psql -d flask_app_db -U max"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      POSTGRES_DB: "flask_app_db"
      POSTGRES_USER: "max"
      POSTGRES_PASSWORD: "4125"
    hostname: localhost
    ports:
      - "5431:5432"

  redis:
    depends_on:
      - db
    image: redis:7.2
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 100s
    ports:
      - "6379:6379"
    volumes:
      - $PWD/volume/data:/root/redis
      # - $PWD/volume/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=4125
      - REDIS_PORT=6379
      - REDIS_DATABASE=1
    
    